use crate::{
    base::{Size, SpeedType},
    impl_mut_player,
    player::CoreAbility,
};

impl_mut_player! {
    pub enum Race {
        // Common
        Dragonborn,
        Dwarf,
        Elf,
        Gnome,
        HalfElf,
        HalfOrc,
        Halfing,
        Human,
        Tiefling,
        // Exotic
        Aarakocra,
        Aasimar,
        Changeling,
        DeepGnome,
        Duergar,
        Eladrin,
        Fairy,
        Firbolg,
        AirGenasi,
        EarthGenasi,
        FireGenasi,
        WaterGenasi,
        Githyanki,
        Githzerai,
        Goliath,
        Harengon,
        Kenku,
        Locathah,
        Owlin,
        Satyr,
        SeaElf,
        ShaderKai,
        Tabaxi,
        Tortle,
        Triton,
        Verdan,
        // Monstrous
        Bugbear,
        Centaur,
        Goblin,
        Grung,
        Hobgobling,
        Kobold,
        Lizardfolk,
        Minotaur,
        Orc,
        Shifter,
        YuanTi,
        // Setting specific
        Kender,
        Kalashtar,
        Warforged,
        Aetherborn,
        Aven,
        Khenra,
        Kor,
        Merfolk,
        Naga,
        Siren,
        Vampire,
        Dhampir,
        Hexblood,
        Reborn,
        Loxodon,
        SimicHybrid,
        Vedalken,
        AstralElf,
        Autognome,
        Giff,
        Hadozee,
        Plasmoid,
        Thrikreen,
        Leonin,
    }

    module = race;

    // The common block now receives the options as well
    common(race, p, _opts) => {
        // Handle ASIs
        p.apply_asi(race.into_asi());
        p.size = race.into_size();

        let speed = race.into_speed();
        p.overwrite_speeds(speed);
    }
}

// Common race traits (ASI, size, speeds)
impl Race {
    pub fn into_asi(&self) -> Vec<(CoreAbility, isize)> {
        match self {
            Race::Dragonborn => vec![(CoreAbility::Strength, 2), (CoreAbility::Charisma, 1)],
            Race::Dwarf => vec![(CoreAbility::Constitution, 2)], // Minor ASI depends on type of dwarf
            Race::Elf => todo!(),
            Race::Gnome => todo!(),
            Race::HalfElf => todo!(),
            Race::HalfOrc => todo!(),
            Race::Halfing => todo!(),
            Race::Human => todo!(),
            Race::Tiefling => todo!(),
            Race::Aarakocra => todo!(),
            Race::Aasimar => todo!(),
            Race::Changeling => todo!(),
            Race::DeepGnome => todo!(),
            Race::Duergar => todo!(),
            Race::Eladrin => todo!(),
            Race::Fairy => todo!(),
            Race::Firbolg => todo!(),
            Race::AirGenasi => todo!(),
            Race::EarthGenasi => todo!(),
            Race::FireGenasi => todo!(),
            Race::WaterGenasi => todo!(),
            Race::Githyanki => todo!(),
            Race::Githzerai => todo!(),
            Race::Goliath => todo!(),
            Race::Harengon => todo!(),
            Race::Kenku => todo!(),
            Race::Locathah => todo!(),
            Race::Owlin => todo!(),
            Race::Satyr => todo!(),
            Race::SeaElf => todo!(),
            Race::ShaderKai => todo!(),
            Race::Tabaxi => todo!(),
            Race::Tortle => todo!(),
            Race::Triton => todo!(),
            Race::Verdan => todo!(),
            Race::Bugbear => todo!(),
            Race::Centaur => todo!(),
            Race::Goblin => todo!(),
            Race::Grung => todo!(),
            Race::Hobgobling => todo!(),
            Race::Kobold => todo!(),
            Race::Lizardfolk => todo!(),
            Race::Minotaur => todo!(),
            Race::Orc => todo!(),
            Race::Shifter => todo!(),
            Race::YuanTi => todo!(),
            Race::Kender => todo!(),
            Race::Kalashtar => todo!(),
            Race::Warforged => todo!(),
            Race::Aetherborn => todo!(),
            Race::Aven => todo!(),
            Race::Khenra => todo!(),
            Race::Kor => todo!(),
            Race::Merfolk => todo!(),
            Race::Naga => todo!(),
            Race::Siren => todo!(),
            Race::Vampire => todo!(),
            Race::Dhampir => todo!(),
            Race::Hexblood => todo!(),
            Race::Reborn => todo!(),
            Race::Loxodon => todo!(),
            Race::SimicHybrid => todo!(),
            Race::Vedalken => todo!(),
            Race::AstralElf => todo!(),
            Race::Autognome => todo!(),
            Race::Giff => todo!(),
            Race::Hadozee => todo!(),
            Race::Plasmoid => todo!(),
            Race::Thrikreen => todo!(),
            Race::Leonin => todo!(),
        }
    }

    pub fn into_size(&self) -> Size {
        match self {
            Race::Dragonborn => Size::Medium,
            Race::Dwarf => Size::Medium,
            Race::Elf => todo!(),
            Race::Gnome => todo!(),
            Race::HalfElf => todo!(),
            Race::HalfOrc => todo!(),
            Race::Halfing => todo!(),
            Race::Human => todo!(),
            Race::Tiefling => todo!(),
            Race::Aarakocra => todo!(),
            Race::Aasimar => todo!(),
            Race::Changeling => todo!(),
            Race::DeepGnome => todo!(),
            Race::Duergar => todo!(),
            Race::Eladrin => todo!(),
            Race::Fairy => todo!(),
            Race::Firbolg => todo!(),
            Race::AirGenasi => todo!(),
            Race::EarthGenasi => todo!(),
            Race::FireGenasi => todo!(),
            Race::WaterGenasi => todo!(),
            Race::Githyanki => todo!(),
            Race::Githzerai => todo!(),
            Race::Goliath => todo!(),
            Race::Harengon => todo!(),
            Race::Kenku => todo!(),
            Race::Locathah => todo!(),
            Race::Owlin => todo!(),
            Race::Satyr => todo!(),
            Race::SeaElf => todo!(),
            Race::ShaderKai => todo!(),
            Race::Tabaxi => todo!(),
            Race::Tortle => todo!(),
            Race::Triton => todo!(),
            Race::Verdan => todo!(),
            Race::Bugbear => todo!(),
            Race::Centaur => todo!(),
            Race::Goblin => todo!(),
            Race::Grung => todo!(),
            Race::Hobgobling => todo!(),
            Race::Kobold => todo!(),
            Race::Lizardfolk => todo!(),
            Race::Minotaur => todo!(),
            Race::Orc => todo!(),
            Race::Shifter => todo!(),
            Race::YuanTi => todo!(),
            Race::Kender => todo!(),
            Race::Kalashtar => todo!(),
            Race::Warforged => todo!(),
            Race::Aetherborn => todo!(),
            Race::Aven => todo!(),
            Race::Khenra => todo!(),
            Race::Kor => todo!(),
            Race::Merfolk => todo!(),
            Race::Naga => todo!(),
            Race::Siren => todo!(),
            Race::Vampire => todo!(),
            Race::Dhampir => todo!(),
            Race::Hexblood => todo!(),
            Race::Reborn => todo!(),
            Race::Loxodon => todo!(),
            Race::SimicHybrid => todo!(),
            Race::Vedalken => todo!(),
            Race::AstralElf => todo!(),
            Race::Autognome => todo!(),
            Race::Giff => todo!(),
            Race::Hadozee => todo!(),
            Race::Plasmoid => todo!(),
            Race::Thrikreen => todo!(),
            Race::Leonin => todo!(),
        }
    }

    pub fn into_speed(&self) -> Vec<(SpeedType, usize)> {
        match self {
            Race::Dragonborn => vec![(SpeedType::Walking, 30)],
            Race::Dwarf => vec![(SpeedType::Walking, 25)],
            Race::Elf => todo!(),
            Race::Gnome => todo!(),
            Race::HalfElf => todo!(),
            Race::HalfOrc => todo!(),
            Race::Halfing => todo!(),
            Race::Human => todo!(),
            Race::Tiefling => todo!(),
            Race::Aarakocra => todo!(),
            Race::Aasimar => todo!(),
            Race::Changeling => todo!(),
            Race::DeepGnome => todo!(),
            Race::Duergar => todo!(),
            Race::Eladrin => todo!(),
            Race::Fairy => todo!(),
            Race::Firbolg => todo!(),
            Race::AirGenasi => todo!(),
            Race::EarthGenasi => todo!(),
            Race::FireGenasi => todo!(),
            Race::WaterGenasi => todo!(),
            Race::Githyanki => todo!(),
            Race::Githzerai => todo!(),
            Race::Goliath => todo!(),
            Race::Harengon => todo!(),
            Race::Kenku => todo!(),
            Race::Locathah => todo!(),
            Race::Owlin => todo!(),
            Race::Satyr => todo!(),
            Race::SeaElf => todo!(),
            Race::ShaderKai => todo!(),
            Race::Tabaxi => todo!(),
            Race::Tortle => todo!(),
            Race::Triton => todo!(),
            Race::Verdan => todo!(),
            Race::Bugbear => todo!(),
            Race::Centaur => todo!(),
            Race::Goblin => todo!(),
            Race::Grung => todo!(),
            Race::Hobgobling => todo!(),
            Race::Kobold => todo!(),
            Race::Lizardfolk => todo!(),
            Race::Minotaur => todo!(),
            Race::Orc => todo!(),
            Race::Shifter => todo!(),
            Race::YuanTi => todo!(),
            Race::Kender => todo!(),
            Race::Kalashtar => todo!(),
            Race::Warforged => todo!(),
            Race::Aetherborn => todo!(),
            Race::Aven => todo!(),
            Race::Khenra => todo!(),
            Race::Kor => todo!(),
            Race::Merfolk => todo!(),
            Race::Naga => todo!(),
            Race::Siren => todo!(),
            Race::Vampire => todo!(),
            Race::Dhampir => todo!(),
            Race::Hexblood => todo!(),
            Race::Reborn => todo!(),
            Race::Loxodon => todo!(),
            Race::SimicHybrid => todo!(),
            Race::Vedalken => todo!(),
            Race::AstralElf => todo!(),
            Race::Autognome => todo!(),
            Race::Giff => todo!(),
            Race::Hadozee => todo!(),
            Race::Plasmoid => todo!(),
            Race::Thrikreen => todo!(),
            Race::Leonin => todo!(),
        }
    }
}
